# Generated by Django 3.2.6 on 2021-08-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0002_weapon_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
