# Generated by Django 3.2.6 on 2021-08-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0003_alter_weapon_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='description',
        ),
        migrations.AddField(
            model_name='weapon',
            name='passive',
            field=models.TextField(null=True),
        ),
    ]
