# Generated by Django 3.2.6 on 2021-09-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('pic', models.TextField(default='')),
                ('user', models.IntegerField(default=1)),
                ('hp', models.FloatField()),
                ('attack', models.FloatField()),
                ('defence', models.FloatField()),
                ('em', models.FloatField()),
                ('stamina', models.FloatField()),
                ('critRate', models.FloatField()),
                ('critDmg', models.FloatField()),
                ('selfHeal', models.FloatField()),
                ('othersHeal', models.FloatField()),
                ('recharge', models.FloatField()),
                ('cdReduction', models.FloatField()),
                ('shield', models.FloatField()),
                ('pyroDmg', models.FloatField()),
                ('pyroRes', models.FloatField()),
                ('hydroDmg', models.FloatField()),
                ('hydroRes', models.FloatField()),
                ('dendroDmg', models.FloatField()),
                ('dendroRes', models.FloatField()),
                ('electroDmg', models.FloatField()),
                ('electroRes', models.FloatField()),
                ('anemoDmg', models.FloatField()),
                ('anemoRes', models.FloatField()),
                ('cryoDmg', models.FloatField()),
                ('cryoRes', models.FloatField()),
                ('geoDmg', models.FloatField()),
                ('geoRes', models.FloatField()),
                ('physDmg', models.FloatField()),
                ('physRes', models.FloatField()),
            ],
        ),
    ]
