# Generated by Django 3.2.6 on 2021-11-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_auto_20210904_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ascStat',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='character',
            name='ascension',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='character',
            name='attack',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='character',
            name='defence',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hp',
            field=models.TextField(default='[]'),
        ),
    ]
