# Generated by Django 3.2.6 on 2021-08-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_character_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='user',
            field=models.IntegerField(default=1),
        ),
    ]
