# Generated by Django 3.2.6 on 2021-08-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_alter_character_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='pic',
            field=models.TextField(default=''),
        ),
    ]
