# Generated by Django 3.2.6 on 2021-09-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('type', models.IntegerField()),
                ('passive', models.TextField(default='none')),
                ('attack', models.FloatField(default=0)),
                ('statTitle', models.TextField(default='none', null=True)),
                ('stat', models.FloatField(default=0)),
            ],
        ),
    ]
