# Generated by Django 3.2.6 on 2021-11-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='pic',
            field=models.TextField(default='none'),
        ),
    ]
