# Generated by Django 3.2.6 on 2021-11-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0002_weapon_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='rarity',
            field=models.IntegerField(default=1),
        ),
    ]
