# Generated by Django 3.2.6 on 2021-11-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0003_weapon_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='attack',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='stat',
            field=models.TextField(default='[]'),
        ),
    ]
