# Generated by Django 3.2.6 on 2021-09-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('twopcEffect', models.TextField(default='none')),
                ('fourpcEffect', models.TextField(default='none')),
                ('element', models.TextField(default='none')),
                ('twopcBonus', models.TextField(default='none')),
                ('twopcStats', models.FloatField(default='none')),
                ('fourpcBonus', models.TextField(default='none')),
            ],
        ),
    ]
