# Generated by Django 3.2.6 on 2021-09-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0002_auto_20210903_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='fourpc',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='twopc',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='tag',
            field=models.TextField(default='short form'),
        ),
    ]
